FROM debian

RUN apt update -y && apt upgrade -y

RUN apt install -y bzip2 libsdl-image1.2 libsdl-ttf2.0-0 libgtk2.0-0 libglu1-mesa libopenal1

WORKDIR /root

ADD http://www.bay12games.com/dwarves/df_44_12_linux.tar.bz2 dwarf.tar.bz2

RUN tar xvf dwarf.tar.bz2

WORKDIR /root/df_linux

RUN sed -i "s/PRINT_MODE:2D/PRINT_MODE:TEXT/g" data/init/init.txt

ENTRYPOINT ./df
